const Images = [
  "./artImages/no23.png",
  "./artImages/no22.png",
  "./artImages/no21.png",
  "./artImages/no20.jpg",
  "./artImages/no19.jpg",
  "./artImages/no1.png",
  "./artImages/no2.jpg",
  "./artImages/no3.jpg",
  "./artImages/no4.jpg",
  "./artImages/no5.jpg",
  "./artImages/no6.png",
  "./artImages/no7.png",
  "./artImages/no8.jpg",
  "./artImages/no9.jpg",
  "./artImages/no10.png",
  "./artImages/no11.jpg",
  "./artImages/no12.png",
  "./artImages/no13.jpg",
  "./artImages/no14.jpg",
  "./artImages/no15.png",
  "./artImages/no16.png",
  "./artImages/no17.jpg",
  "./artImages/no18.jpg",
];

export default Images;
